### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by johnmaster** [Jinglue/DL4Img#7]
按照您的教程，我使用腾讯云服务器，但是在第九章的代码中，训练集的路径找不到，请问您，这个路径是什么？

**Comment by johnmaster** [comment]
不好意思，以前没用过DOCKER，已经解决问题。

**Comment by huboqiang** [comment]
您好，在 https://github.com/Jinglue/DL4Img/blob/master/notebook/Lecture9/CatDog_v1_cnn.ipynb 第一个 block 中给注释掉了，谢谢。
